[project]
name = "mem0-mcp"
version = "0.2.0"
description = "Simplified MCP server for AI memory management with Mem0"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mcp[cli]>=1.0.0",
    "mem0ai>=0.1.0",
]