services:
  - type: web
    name: mem0-mcp
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        fromGroup: mem0-mcp
      - key: MEM0_API_KEY
        fromGroup: mem0-mcp
      - key: PYTHON_VERSION
        value: "3.12.11"