services:
  - type: web
    name: mem0-mcp
    runtime: python
    buildCommand: ./build.sh
    startCommand: python main_render.py
    envVars:
      - key: MEM0_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.12"
    plan: free